annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/janus-idp/helm-backstage/issues
    - name: Chart Source
      url: https://github.com/janus-idp/helm-backstage
    - name: Default Image Source
      url: https://github.com/janus-idp/backstage-showcase
  charts.openshift.io/name: Backstage
  charts.openshift.io/provider: Janus-IDP
  charts.openshift.io/supportURL: https://github.com/janus-idp/helm-backstage/issues
apiVersion: v2
description: A Helm chart for deploying a Backstage application
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: "2.4.0"
  - name: backstage
    repository: https://backstage.github.io/charts
    version: "1.1.2"
    alias: upstream
home: https://janus-idp.io
icon: https://avatars.githubusercontent.com/u/117844786
keywords:
  - backstage
  - idp
  - janus-idp
kubeVersion: ">= 1.19.0-0"
maintainers:
  - name: Janus-IDP
    url: https://janus-idp.io
name: backstage
type: application
sources:
  - https://github.com/janus-idp/helm-backstage
  - https://github.com/janus-idp/backstage-showcase

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.2.2
