name: Bump

on: issue_comment

jobs:
  chart-version:
    name: Chart Version
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      issues: write

    steps:
      - name: Check for command
        id: command
        continue-on-error: true
        uses: xt0rted/slash-command-action@bf51f8f5f4ea3d58abc7eca58f77104182b23e88 # v2
        with:
          command: bump
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write

      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4
        if: steps.command.outputs.command-name
        with:
          python-version: 3.7

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        if: steps.command.outputs.command-name
        with:
          go-version: ^1

      - name: Setup helm-docs
        if: steps.command.outputs.command-name
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest

      - name: Generate token
        if: steps.command.outputs.command-name
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ vars.JANUS_IDP_GITHUB_APP_ID }}
          private_key: ${{ secrets.JANUS_IDP_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        if: steps.command.outputs.command-name
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Checkout Pull Request
        if: steps.command.outputs.command-name
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Get version
        if: steps.command.outputs.command-name
        id: get_version
        uses: mikefarah/yq@6609ed76ecb69f9d8254345292d90ea72f641715  # v4.35.1
        with:
          cmd: yq ".version" charts/backstage/Chart.yaml

      - uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5  # v1
        if: steps.command.outputs.command-name
        id: semver
        with:
          current_version: ${{ steps.get_version.outputs.result }}
          level: ${{ steps.command.outputs.command-arguments }}

      - name: Bump the version
        if: steps.command.outputs.command-name
        uses: mikefarah/yq@6609ed76ecb69f9d8254345292d90ea72f641715  # v4.35.1
        with:
          cmd: yq -i '.version = "${{ steps.semver.outputs.new_version }}"' charts/backstage/Chart.yaml

      - name: Run pre-commit
        if: steps.command.outputs.command-name
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # renovate: tag=v3.0.0
        continue-on-error: true

      - name: Setup Gitsign
        if: steps.command.outputs.command-name
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit pre-commit changes
        if: steps.command.outputs.command-name
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        with:
          commit_message: Bump version to ${{ steps.semver.outputs.new_version }}
          commit_options: '-s'
          commit_user_name: Janus IDP
          commit_user_email: 139477802+janus-idp[bot]@users.noreply.github.com
          commit_author: Janus IDP <139477802+janus-idp[bot]@users.noreply.github.com>

